#!/bin/sh
uci set ua3f.enabled.enabled='0' > /dev/null 2>&1
uci commit ua3f > /dev/null 2>&1
rm -rf /var/log/ua3f >/dev/null 2>&1
rm -rf /usr/lib/lua/luci/model/cbi/ua3f >/dev/null 2>&1
rm -rf /usr/lib/lua/luci/model/cbi/ua3f.lua >/dev/null 2>&1
rm -rf /usr/lib/lua/luci/controller/ua3f.lua >/dev/null 2>&1
rm -rf /usr/lib/lua/luci/view/ua3f >/dev/null 2>&1
